#!/system/bin/sh



resetprop audio.safemedia.bypass true
resetprop ro.ril.enable.amr.wideband 1

resetprop persist.dev.pm.dyn_samplingrate 1
resetprop dev.pm.dyn_samplingrate 1
resetprop af.resampler.quality 7


resetprop lpa.decode false
resetprop lpa.use-stagefright false
resetprop lpa.releaselock false

resetprop ro.audio.resampler.psd.enable_at_samplerate 44100
resetprop ro.audio.resampler.psd.stopband 196
resetprop ro.audio.resampler.psd.halflength 960
resetprop ro.audio.resampler.psd.cutoff_percent 120
resetprop ro.audio.resampler.psd.tbwcheat 0

ro.media.vol.steps=40




killall mediaserver
killall audioserver




